packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.3.0
  '@commitlint/cli': ^19.8.1
  '@eslint-react/eslint-plugin': ^1.53.1
  '@next/eslint-plugin-next': ^15.5.3
  '@opennextjs/cloudflare': ^1.8.2
  '@radix-ui/react-slot': ^1.2.3
  '@tailwindcss/postcss': ^4.1.13
  '@types/node': ^24.5.0
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitizen: ^4.3.1
  cz-emoji: 1.3.2-canary.2
  eslint: ^9.35.0
  eslint-plugin-drizzle: ^0.2.3
  eslint-plugin-format: ^1.0.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-turbo: ^2.5.6
  hono: ^4.9.7
  husky: ^9.1.7
  lint-staged: ^16.1.6
  lucide-react: ^0.544.0
  next: ^15.5.3
  next-themes: ^0.4.6
  pino: ^9.9.5
  pino-pretty: ^13.1.1
  postcss: ^8.5.6
  react: ^19.1.1
  react-dom: ^19.1.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  turbo: ^2.5.6
  tw-animate-css: ^1.3.8
  typescript: 5.9.2
  vitest: ^3.2.4
  wrangler: ^4.37.0
