packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@antfu/eslint-config': ^4.14.1
  '@cloudflare/workers-types': ^4.20250614.0
  '@commitlint/cli': ^19.8.1
  '@eslint-react/eslint-plugin': ^1.52.2
  '@next/eslint-plugin-next': ^15.3.3
  '@opennextjs/cloudflare': ^1.3.0
  '@radix-ui/react-slot': ^1.2.3
  # eslint-disable-next-line pnpm/yaml-no-unused-catalog-item
  '@tailwindcss/oxide': ^0.1.0
  '@tailwindcss/postcss': ^4.1.10
  '@types/node': ^24.0.3
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.6
  '@yorganci/eslint-plugin-tailwindcss': ^0.0.7
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitizen: ^4.3.1
  cz-emoji: 1.3.2-canary.2
  # eslint-disable-next-line pnpm/yaml-no-unused-catalog-item
  esbuild: ^0.15.15
  eslint: ^9.29.0
  eslint-plugin-drizzle: ^0.2.3
  eslint-plugin-format: ^1.0.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-turbo: ^2.5.4
  hono: ^4.7.11
  husky: ^9.1.7
  lint-staged: ^16.1.2
  lucide-react: ^0.522.0
  next: ^15.3.3
  next-themes: ^0.4.6
  pino: ^9.7.0
  pino-pretty: ^13.0.0
  postcss: ^8.5.6
  react: ^19.1.0
  react-dom: ^19.1.0
  # eslint-disable-next-line pnpm/yaml-no-unused-catalog-item
  sharp: ^0.32.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.10
  turbo: ^2.5.4
  tw-animate-css: ^1.3.4
  typescript: 5.8.2
  vitest: ^3.2.3
  # eslint-disable-next-line pnpm/yaml-no-unused-catalog-item
  workerd: ^0.1.0
  wrangler: ^4.20.0
onlyBuiltDependencies:
  - esbuild
  - workerd
  - sharp
  - '@tailwindcss/oxide'
