# eslint-disable pnpm/yaml-no-unused-catalog-item
packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^4.16.1
  '@cloudflare/workers-types': ^4.20250628.0
  '@commitlint/cli': ^19.8.1
  '@eslint-react/eslint-plugin': ^1.52.2
  '@next/eslint-plugin-next': ^15.3.4
  '@opennextjs/cloudflare': ^1.3.1
  '@radix-ui/react-slot': ^1.2.3
  '@tailwindcss/oxide': ^0.1.0
  '@tailwindcss/postcss': ^4.1.11
  '@types/node': ^24.0.7
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@yorganci/eslint-plugin-tailwindcss': ^0.0.7
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitizen: ^4.3.1
  cz-emoji: 1.3.2-canary.2
  esbuild: ^0.15.15
  eslint: ^9.30.0
  eslint-plugin-drizzle: ^0.2.3
  eslint-plugin-format: ^1.0.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-turbo: ^2.5.4
  hono: ^4.8.3
  husky: ^9.1.7
  lint-staged: ^16.1.2
  lucide-react: ^0.525.0
  next: ^15.3.4
  next-themes: ^0.4.6
  pino: ^9.7.0
  pino-pretty: ^13.0.0
  postcss: ^8.5.6
  react: ^19.1.0
  react-dom: ^19.1.0
  sharp: ^0.32.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  turbo: ^2.5.4
  tw-animate-css: ^1.3.4
  typescript: 5.8.3
  vitest: ^3.2.4
  workerd: ^0.1.0
  wrangler: ^4.22.0

onlyBuiltDependencies:
  - esbuild
  - workerd
  - sharp
  - '@tailwindcss/oxide'
