name: Auto Merge

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: 'Automated PR merge'
        uses: 'pascalgn/automerge-action@v0.16.3'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: 'automerge'
